style category and footer sections
Janussz/Travel-New pull request #2
Opened 2022-05-10 17:24 UTC by Janussz

## Zrobione:
- footer
- category
- subscribe
- button
- setup kolorów
- mixiny dla fontów i flexa
- klasy tekstowe
- font załączony

## Do dokończenia:
- poprawa elementów w sekcji category
- poprawa nazewnictwa
- poprawa inputa w subscribe
- javascript do większości sekcji

2022-05-10 17:36 UTC, TomaszFeszter reviewed
@Janussz Dlaczego dodałeś niektóre ikony poza plikiem zbiorowym?
Należy usunąć plik `mail2.svg`
Wszystkie ikony powinny znajdować się w pliku `symbol-defs.svg`

2022-05-10 17:46 UTC, TomaszFeszter commented on index.html
> +            <button class="subscribe__btn">Subscribe</button>
Należy zmienić nazwę na bardziej uniwersalną

2022-05-10 17:59 UTC, TomaszFeszter commented on sass/components/_buttons.scss
> +  height: 3.8rem;
Należy usunąć `height`.
`width` zmienić na `max-width`.
Wielkość guzika zaimplementować za pomocą `padding`.

2022-05-10 18:02 UTC, TomaszFeszter commented on sass/components/_container.scss
> +
Właściwość `margin` może kolidować z innymi sekcjami.
Proponuję zmianę na `padding` ustawić na wartość `2rem`

2022-05-10 18:05 UTC, TomaszFeszter commented on sass/components/_icones.scss
> +.facebook .tweeter {
Brakuje przecinka w selektorze.
Rozważyłbym czy selektor jest potrzebny.

2022-05-10 18:08 UTC, TomaszFeszter commented on sass/components/_services.scss
> +  &__list--item:hover {
Trzeba inaczej zaimplementować zmianę wielkości.
Tak jak zaznaczyłem w dokumencie html zmienić nazwę selektora.

2022-05-10 18:10 UTC, TomaszFeszter commented on sass/layout/_category.scss
> +    right: 1%;
Użycie `%` może być w późniejszej pracy nieprzewidywalne.

2022-05-10 18:14 UTC, TomaszFeszter commented on sass/layout/_subscribe.scss
> +    max-width: 15%;
Zalecam zmianę `%`

2022-05-10 18:17 UTC, TomaszFeszter commented on sass/layout/_subscribe.scss
> +        height: 3.8rem;
Trzeba przerobić całego inputa na komponent.
Usunąć `height` i `width`, zastąpić responsywnymi właściwościami.
Do nadania wielkości użyć `padding`.

2022-05-10 18:19 UTC, TomaszFeszter requested changes
Proszę o poprawienie zakomentowanych linijek.

2022-05-10 19:12 UTC, Janussz commented on index.html
> +          <li class="category__services__list--item">
Ok poprawione

2022-05-10 19:15 UTC, Janussz commented on index.html
> +            <button class="subscribe__btn">Subscribe</button>
Poprawione

2022-05-10 19:22 UTC, Janussz commented on index.html
> +            <input id="s" type="email" class="input_s" placeholder="Your email">
poprawione

2022-05-10 19:40 UTC, Janussz commented on sass/components/_container.scss
> +
poprawione

2022-05-10 19:52 UTC, Janussz commented on sass/components/_icones.scss
> +.facebook .tweeter {
poprawione

2022-05-10 19:52 UTC, Janussz commented on sass/layout/_category.scss
> +    right: 1%;
poprawione

2022-05-10 19:53 UTC, Janussz commented on sass/layout/_subscribe.scss
> +    max-width: 15%;
poprawione

2022-05-11 18:48 UTC, Janussz commented on sass/layout/_subscribe.scss
> +        height: 3.8rem;
poprawione

2022-05-11 18:48 UTC, Janussz commented on sass/components/_services.scss
> +  &__list--item:hover {
poprawione

2022-05-15 10:46 UTC, TomaszFeszter approved these changes
Dobra robota :)

2022-05-15 10:47 UTC, merged